### ISSUE TITLE
iOS bug?

### ISSUE THREAD

**Issue by drking** [javalent/prominent-files#6]
I love this plug-in. Thank you! Just a few questions. 
(1.) Is there a way to have stars show up on the left instead of the right? 
(2.) (bug?) Also, I don’t see the plug-in enabled under the list installed community plug-ins after installation and enabling. Is that meant to be?

using iOS 16, latest developer, beta, iPad Pro

**Comment by sigrunixia** [comment]
@drking 
Are you still having an issue with the second question? In the meantime, I have marked your first issue as a feature request.
